# Generated by Django 4.1.6 on 2023-03-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationschedule',
            name='desc',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
