# Generated by Django 4.1.6 on 2023-03-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='chapters',
        ),
    ]
